language: node_js
node_js:
  - "node"
env:
  - NODE_ENV=ci
cache:
  directories:
  - node_modules
install:
  - npm install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - npm run build:prod
  - npm test
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x config/deploy.sh && config/deploy.sh
  on:
    branch: prod
