language: node_js
node_js:
  - "node"
env:
  - NODE_ENV=ci
cache:
  directories:
  - node_modules
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - npm run build:prod
  - npm test
deploy:
  skip_cleanup: true
  provider: script
  script: config/deploy.sh
  on:
    branch: master
